# Generated by Django 5.2 on 2025-05-01 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=18, verbose_name="Баланс карты"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="card",
            name="card_number",
            field=models.PositiveBigIntegerField(
                unique=True, verbose_name="Номер карты"
            ),
        ),
        migrations.AlterField(
            model_name="card",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddConstraint(
            model_name="card",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("card_number__gte", 1000000000000000),
                    ("card_number__lte", 9999999999999999),
                ),
                name="card_number_16_digits",
            ),
        ),
    ]
