# Generated by Django 5.2 on 2025-05-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_card_balance_alter_card_card_number_alter_card_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="card",
            options={
                "verbose_name": "Банковская карта",
                "verbose_name_plural": "Банковские карты",
            },
        ),
        migrations.AlterField(
            model_name="card",
            name="active_until",
            field=models.DateField(verbose_name="Активна до"),
        ),
    ]
