# Generated by Django 5.2 on 2025-05-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0003_alter_card_options_alter_card_active_until"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="balance",
        ),
    ]
