# Generated by Django 5.2 on 2025-05-01 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("goal_name", models.CharField(max_length=255, verbose_name="Цель")),
                (
                    "approximate_cost",
                    models.PositiveBigIntegerField(
                        verbose_name="Приблизительная стоимость"
                    ),
                ),
                (
                    "execution_date",
                    models.DateTimeField(verbose_name="Срок выполнения"),
                ),
            ],
            options={
                "verbose_name": "Цель",
                "verbose_name_plural": "Цели",
            },
        ),
    ]
