# Generated by Django 5.2 on 2025-05-01 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cards", "0002_card_balance_alter_card_card_number_alter_card_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(max_length=128, verbose_name="Категория"),
                ),
            ],
            options={
                "verbose_name": "Категория транзакции",
                "verbose_name_plural": "Категории транзакций",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=18, verbose_name="Сумма транзакции"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "Income"), ("EX", "Expense")],
                        verbose_name="Тип транзакции",
                    ),
                ),
                (
                    "receiver",
                    models.CharField(
                        max_length=255, verbose_name="Получатель транзакции"
                    ),
                ),
                ("transaction_date", models.DateTimeField(auto_now=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cards.card",
                        verbose_name="Банковская карта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Транзакция",
                "verbose_name_plural": "Транзакции",
            },
        ),
    ]
