# Generated by Django 5.2 on 2025-05-01 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="transactions.transactioncategory",
                verbose_name="Категория",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="transaction",
            name="transaction_type",
            field=models.CharField(
                choices=[("IN", "Поступление"), ("EX", "Трата")],
                verbose_name="Тип транзакции",
            ),
        ),
    ]
