# Generated by Django 5.2 on 2025-05-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0002_transaction_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="receiver",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Получатель транзакции",
            ),
        ),
    ]
