# Generated by Django 5.2 on 2025-05-01 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transactions", "0003_alter_transaction_receiver"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата транзакции"),
        ),
    ]
